# CloudResource for Platform Engineering Workshop
# A CloudResource is a user's request for infrastructure
# It references a Plan (template) and provides variable values
#
# This is what a developer would create to get infrastructure provisioned

apiVersion: terraform.appvia.io/v1alpha1
kind: CloudResource
metadata:
  name: workshop-infra-v2
  namespace: terranetes-deployments
spec:
  # Reference to the Plan (template) to use
  plan:
    name: workshop-infra
    revision: v1.0.0
  
  # Reference to the cloud provider
  providerRef:
    name: azure
  
  # Variable values for this instance - only the unique identifiers needed!
  # All other variables (location, environment, etc.) use sensible defaults
  variables:
    resource_group_name: "rg-geert-terranetes-workshop-dev"  # Make this unique to you
    github_repo_name: "geert-terranetes-workshop-infra"      # Make this unique to you
  
  # Terraform execution settings
  enableAutoApproval: false  # Set to true to auto-approve plans

---
# Instructions for customizing this CloudResource:
#
# 1. Replace "yourname" with your actual name/initials in the variables above
# 2. Make sure resource names are unique to avoid conflicts
# 3. Apply with: kubectl apply -f cloudresource-example.yaml
# 4. Check status: kubectl get cloudresource workshop-infra-v2 -n terranetes-deployments
# 5. View outputs: kubectl get secret workshop-infra -n terranetes-deployments -o yaml
