# CloudResource Example
# A CloudResource is a user's request for infrastructure
# It references a Revision (template) and provides variable values
#
# This is what a developer would create to get infrastructure provisioned

apiVersion: terraform.appvia.io/v1alpha1
kind: CloudResource
metadata:
  name: workshop-infra
  namespace: terraform-deployments
spec:
  # Reference to the Revision (template) to use
  revisionRef:
    name: workshop-infrastructure
    # Optional: pin to specific version
    # version: "v1.0.0"
  
  # Approval settings
  # In production, you might require manual approval
  plan:
    # Automatically approve and apply changes
    approval: automatic
    # Alternative: require manual approval
    # approval: manual
  
  # Enable automatic drift detection and correction
  enableAutoApproval: true
  enableDriftDetection: true
  
  # Variable values for this instance
  # Only required variables need to be specified
  variables:
    resource_group_name: "rg-terranetes-workshop-dev"
    github_repo_name: "terranetes-workshop-infra"
  
  # Write connection details to a Kubernetes secret
  # This makes outputs available to applications
  writeConnectionSecretToRef:
    name: workshop-infra-outputs

---
# Instructions for customizing this CloudResource:
#
# 1. Edit the variables section with your specific values:
#    - resource_group_name: Make unique to avoid conflicts
#    - github_repo_name: Choose a unique repository name
# 2. Apply with: kubectl apply -f cloudresource-example.yaml
# 3. Check status: kubectl get cloudresource workshop-infra -n terraform-deployments
# 4. View outputs: kubectl get secret workshop-infra-outputs -n terraform-deployments -o yaml
