# Infrastructure Revision for Terranetes
# A Revision is a reusable template that platform teams create
# and developers can instantiate via CloudResources
#
# This Revision uses the workshop's OpenTofu module to create:
# - Azure Resource Group
# - GitHub Repository (via Azure provider integration)

apiVersion: terraform.appvia.io/v1alpha1
kind: Revision
metadata:
  name: workshop-infrastructure
spec:
  # Version of this template
  version: "v1.0.0"
  
  # Human-readable description
  description: |
    Creates infrastructure setup for a workshop participant using the 
    workshop's OpenTofu module from the GitHub repository.
    
    This demonstrates how Terranetes can use existing Terraform/OpenTofu 
    modules from Git repositories as cloud provider templates.
  
  # OpenTofu/Terraform configuration
  configuration:
    # Required providers - only Azure for cloud provider compatibility
    providerRefs:
      - name: azure-provider
    
    # Source module from workshop repository
    # Uses the Terranetes-compatible OpenTofu module
    source: "https://github.com/Zure/platform-engineering-workshop.git//lab05/opentofu?ref=main"
  
  # Variables that users must/can provide
  inputs:
    - key: resource_group_name
      description: "Name of the Azure Resource Group to create"
      required: true
      
    - key: github_repo_name
      description: "Name of the GitHub repository to create"
      required: true
