apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: azure
spec:
  provider: azurerm
  source: secret
  secretRef:
    name: azure-credentials
    namespace: terranetes-system
  summary: Azure credentials for Terranetes
