# GitHub Provider for Terranetes
# This resource configures how Terranetes authenticates with GitHub
#
# The provider references a Kubernetes secret containing the GitHub token
# which must be created before applying this resource.

apiVersion: terraform.appvia.io/v1alpha1
kind: Provider
metadata:
  name: github-provider
spec:
  # Human-readable description
  summary: "GitHub provider for Platform Engineering Workshop"
  
  # Provider source (same as in versions.tf)
  source: integrations/github
  
  # Provider version constraint
  version: "~> 6.0"
  
  # Reference to the Kubernetes secret containing credentials
  # The secret must contain:
  # - GITHUB_TOKEN
  secretRef:
    name: github-credentials
    namespace: terraform-deployments

---
# Instructions for creating the required secret:
#
# kubectl create secret generic github-credentials \
#   --namespace terraform-deployments \
#   --from-literal=GITHUB_TOKEN="ghp_your_token_here"
#
# To create a GitHub Personal Access Token:
# 1. Go to https://github.com/settings/tokens
# 2. Click "Generate new token" -> "Generate new token (classic)"
# 3. Give it a name: "terranetes-workshop"
# 4. Select scopes: repo, delete_repo
# 5. Click "Generate token"
# 6. Copy the token immediately!
